mybatis-flex:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/exam?serverTimezone=Asia/Shanghai&timezone=GMT+8&useUnicode=true&characterEncoding=utf-8
      username: eaxm
      password: 20250829
      type: com.alibaba.druid.pool.DruidDataSourcea